name: Test

on:
  pull_request:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: add_to_estuary
      uses: ./
      with:
        estuary_api_token: ${{ secrets.ESTUARY_TOKEN }}
        path_to_add: 'test/fixtures'
    - run: echo ${{ steps.add_to_estuary.outputs.url }}
